### PR TITLE
Add itBit exchange/ticker

### PR DESCRIPTION
**Pull request by chrisrico**
Still need to an an error handler to extract information about failed calls.

It was unclear how to compile elm.js so I edited it by hand.

### CODE REVIEW

**Comment by chrisrico** [comment]
We recently ordered a Sintra Forte and we use ItBit as our exchange provider.

**Comment by joshmh** [comment]
Thanks @chrisrico! We've put it on our priority list, although it still might take some time before it's merged.

**Comment by chrisrico** [comment]
Is there anything I can do to speed up the process?

**Comment by joshmh** [comment]
You can check back in a week. We'll let you know if we have any questions once we look at it more carefully.

**Comment by chrisrico** [comment]
Ok, thanks. Didn't meant to imply there was any rush, we won't have our machine until next month at the earliest, and it probably won't be in operation until early 2019.

**Comment by joshmh** [comment]
Cool, shouldn't be a problem then :)

**Pull request closed without merging**
