### PR TITLE
More descriptive SMS alerts

### PR DESCRIPTION
**Pull request by naconner**
Instead of subject, which does not specify the individual machine for which there are alerts, instead use email alert text for SMS.

### CODE REVIEW

**Comment by joshmh** [comment]
Won't this be too long for an SMS?

**Comment by naconner** [comment]
Soft limit is 160 characters, this is 96 characters:

```
Errors were reported by your Lamassu Machines.

Errors for Test Machine:
Machine down for ~1 minute
```

Twilio will split anything over 160 characters into multiple messages, which shouldn't be minded given the utility of the alerts: https://www.twilio.com/docs/glossary/what-sms-character-limit

**Comment by joshmh** [comment]
@naconner ping.

**Comment by naconner** [comment]
Makes sense. I can try a few things. Issue I had with it in testing was that no changes to notifier.js were reflected in new SMS alerts, despite restarting l-s and the server itself. Only by installing on a fresh droplet from a branch with that change was it finally reflected.

**Comment by joshmh** [comment]
@naconner Only thing that makes sense to me is that there was a prefix issue and your were running different code than you changed.

**Comment by joshmh** [comment]
Closing this for now.

**Pull request closed without merging**
