### PR TITLE
Trade on USD Kraken if fiat is other than USD/EUR

### PR DESCRIPTION
**Pull request by naconner**
If a machine currency is other than USD or EUR, Kraken trades will fail because pair is not defined in `common/kraken.js` (and not offered by Kraken).

Instead, trade on USD market.

### CODE REVIEW

**Comment by joshmh** [comment]
Have you talked to operators to see if this is their desired behavior? How do we know if they want EUR or USD?

**Comment by naconner** [comment]
Unless we create an admin-based selector for USD vs EUR market, this brings it in line with expectations we can set in knowledgebase documentation.  The USD market has greater depth, and Kraken is a U.S.-based exchange. (Our Bitstamp trader had been USD-market only, even though EUR pairs existed, and we set this expectation without issue.)

**Comment by joshmh** [comment]
Kraken has much higher EUR liquidity than USD. Should we still choose USD for Kraken?

**Comment by naconner** [comment]
Ah, my bad. Using EUR makes sense then, also since more currencies exist around the Eurozone than the U.S., and they may have SEPA transfers and better rates for EUR conversion.

**Comment by naconner** [comment]
@joshmh Now defaulting to EUR. All set?

**Pull request merged**
